version: '3.7'

services:
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
#      MINIO_CONSOLE_ADDRESS: ":9001"
    command: server /data --console-address ":9001"

volumes:
  minio_data:
